# Site Settings
title: Pavan Ravi
email: pavanr2@illinois.edu
description: >-
  Ph.D. @ UIUC | Computational Mechanics | HPC 

# URLs
baseurl: ""
url: "https://pavanr25.github.io"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Minima theme customizations
minima:
  social_links:
    github: pavanr25